site_name: FIN-Warrah's Blog
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 计算机图形学:
    - opengl
  - LeetCode:
    - 学习计划-数据结构: LeetCode/学习计划_数据结构.md
  - 实用工具: 
    - Git 与 GitHub:
      - 1 上传此博客到 GitHub: 实用工具/Git与GitHub/1_上传此博客到GitHub.md
    - Shell: 实用工具/Shell.md
    - 实用工具: 实用工具/实用工具.md